### ISSUE TITLE
Funcionalidades: Implementar migración de código a Angular (versión 17) en la página Quienes Somos

### ISSUE THREAD

**Issue by Leopladom** [CodeSquadISPC/CodeSquadRepoFrontend#11]
#TK08

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la página Quienes Somos del frontend. Esta tarea implica la creación de un componente Quienes. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente Quienes Somos se ha creado y se ha integrado correctamente.
2. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
3. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![quienes](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/16c09c13-ce84-43c5-8aa8-3b7a34661b50)

**Comment by nahir1009** [comment]
El código existente de la pagina quienes somos Frontend se  ha migrado a Angular 17 de forma correcta  y se cumplió con los siguientes criterios :
 1)se agrego el componente quienes a su carpeta Pages con su respectivo código HTML y css correctamente.
 2) se agrego Databinding interpolación a los textos. 
 3) se migraron esos datos y guardaron en services.
