### ISSUE TITLE
Funcionalidades: Implementar migración de código a Angular (versión 17) en la página de Contacto

### ISSUE THREAD

**Issue by Leopladom** [CodeSquadISPC/CodeSquadRepoFrontend#13]
**#TK01**

_Descripción:_
Se requiere migrar el código JavaScript existente a Angular (versión 17) en la página de Contacto del frontend. Esta tarea implica la creación de un componente de Contacto y la implementación de un formulario reactivo. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente de Contacto se ha creado y se ha integrado correctamente.
2. Se ha implementado un formulario reactivo que permite la entrada de datos.
3. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
4. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![contacto](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/c1478582-fec6-4e3a-a86a-3782a28708c0)

**Comment by IvetteJN** [comment]
El componente de Contacto se ha creado y se ha integrado correctamente.
Se ha implementado un formulario reactivo que permite la entrada de datos.
Se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
Se han utilizado servicios para proporcionar datos.
