### ISSUE TITLE
#TK06: Funcionalidades: Implementar migración de código a Angular (versión 17) en la página de Login

### ISSUE THREAD

**Issue by Leopladom** [CodeSquadISPC/CodeSquadRepoFrontend#14]
#TK06

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la página de Login del frontend. Esta tarea implica la creación de un componente de Contacto y la implementación de un formulario reactivo. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente de Login se ha creado y se ha integrado correctamente.
2. Se ha implementado un formulario reactivo que permite la entrada de datos.
3. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
4. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 
![login](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/adc10f53-d163-4522-88f8-3b054e524c1b)

**Comment by FrancoR-Orellana** [comment]
El componente de Login se ha creado y se ha integrado correctamente.
Se ha implementado un formulario reactivo que permite la entrada de datos.
Se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.

**Comment by IvetteJN** [comment]
Se abre #49 Task 15 para satisfacer el opcional de servicios
