### ISSUE TITLE
Funcionalidades: componente footer

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#16]
Frontend: Migración de código JavaScript a Angular (versión 17 según requerido).

Componente footer

Opcional: proveer datos mediante el enlace de datos (data binding)
Opcional: Proveer datos mediante servicios. 
Si los opcionales no se realizan en este Sprint, crear nuevo issue enlazado al Sprint 2 para un futuro desarrollo.

![footer](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/9ae1d558-dd5c-42d3-961a-67a647d33937)

**Comment by ldlmarcelo** [comment]
Listo el footer.
