### ISSUE TITLE
#TK03: Funcionalidades: Implementar migración de código a Angular (versión 17) Header/Navbar

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#17]
#TK03

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la etiqueta header/nav del frontend. Esta tarea implica la creación de un componente Nav. Habilitar las rutas de los elementos incluidos en el menú del navbar para poder visualizarlos en el cuerpo de la app (SPA). Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente de Nav se ha creado y se ha integrado correctamente.
2. Se puede acceder a las demás páginas mediante los botones del menú del nav.
3. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
4. Opcionalmente, se han utilizado servicios para proporcionar datos.
Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![navbar](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/0f5ea99b-3d2e-4af5-9ca1-4c548caabd82)

**Comment by AnaliaPellicer** [comment]
El código existente de la etiqueta header/nav del frontend Frontend se ha migrado a Angular 17 de forma correcta y se cumplió con los siguientes criterios:
1)El componente de Nav se ha creado y se ha integrado correctamente con su respectivo código HTML y css correctamente.
2) Se puede acceder a las demás páginas mediante los botones del menú de navegación.

Se crea un nuevo issue para realizar los elementos opcionales que no se pudieron desarrollar en este Sprit
