### ISSUE TITLE
#US04: Agregar más unidades (carrito de compra)

### ISSUE THREAD

**Issue by VirginiaFalconi** [CodeSquadISPC/CodeSquadRepoFrontend#21]
Como usuario: quiero poder agregar mas unidades del libro a comprar y también poder restar, en caso de querer llevar menos cantidad. 

Criterios de aceptación: 
Debemos tener 2 botones, un "+" y un  "-", que nos permitan visualizar el número de unidades que saquemos y agreguemos.

**Comment by IvetteJN** [comment]
trabajado con #83 #TK31
