### ISSUE TITLE
#TK09: Funcionalidades: Crear componente Dashboard (panel de control)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#24]
#TK09

_Descripción:_
Se requiere crear un componente en Angular (versión 17) Dashboard (panel de control). Se ingresará a este componente por medio del ingreso del usuario desde el componente Ingreso. El diseño debería continuar las líneas de diseño de las demás páginas. La imagen adjunta es una guía.
Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente Dashboard se ha creado y se ha integrado correctamente.
2. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
3. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![dashboard example](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/e206b55b-8790-4f50-9ae0-b05c0eea42b7)

**Comment by nahir1009** [comment]
se creado el componente dashboard y  se ha integrado correctamente.
data binding y servicios agreagados a task #49 14.
