### ISSUE TITLE
Funcionalidades: Implementar migración de código a Angular (versión 17) en la página de producto (carrusel)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#27]
#TK10

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la página de producto (carrusel debajo del header/nav) del frontend. Esta tarea implica la creación de un componente Carrusel y su implementación dentro del componente Producto. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente Landing se ha creado y se ha integrado correctamente.
2. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
3. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![carrusel](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/fee813c0-d8dc-4d67-bd98-036c12af3c96)

**Comment by ldlmarcelo** [comment]
gestionado. se tuvo que crear el componente carrusel como hijo de Nuestra Seleccion que también se creó y ruteó para que quede funcional.
