### ISSUE TITLE
#TK12: Funcionalidades: Implementar migración de código a Angular (versión 17) en la página de producto (CarritoCompras)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#42]
#TK12

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la página de producto (carrito de compras) del frontend. Esta tarea implica la creación de un componente Carrito y su implementación dentro del componente Producto. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente Carrito se ha creado y se ha integrado correctamente.
2. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
3. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): https://github.com/CodeSquadISPC/CodeSquadRepoFrontend/issues/40

MARCADO EN VERDE

![producto](https://github.com/CodeSquadISPC/CodeSquadRepoFrontend/assets/100625720/0c810b9a-c5dc-47a0-9c89-bdeddf9bb8dc)

**Comment by Leopladom** [comment]
Criterios de aceptación:

El componente Carrito se ha creado y se ha integrado correctamente.
Los opcionales quedan para un próximo desarrollo. Tarea tratada en la #49 Task 14
