### ISSUE TITLE
#US09: Dashboard vista usuario cliente

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#57]
#US09
Como un usuario que realiza compras en la plataforma de ecommerce de libros, deseo acceder a un dashboard que me proporcione información relevante y funcionalidades útiles para mejorar mi experiencia de compra y seguimiento de pedidos.

_Criterios de Aceptación:_

1. Resumen de Compras:
Quiero ver una vista rápida de mis compras recientes, incluyendo el número de pedido, los productos comprados y el total gastado.
Debería ser fácilmente accesible desde el dashboard principal y actualizarse en tiempo real.
2. Estado del Envío:
Necesito información actualizada sobre el estado de los envíos de mis productos comprados.
Debería incluir la fecha estimada de entrega, el seguimiento del paquete y el medio de envío utilizado.
3. Historial de Compras:
Deseo acceder a un registro completo de mis compras anteriores que hayan sido finalizadas.
Debería ser fácil de navegar y buscar por fecha, número de pedido u otros criterios relevantes.
4. Cupones y Descuentos:
Si hay cupones o descuentos disponibles, quiero poder verlos en el dashboard para aplicarlos durante el proceso de compra.
Deberían estar claramente indicados con sus condiciones de uso.
5. Datos personales:
Una sección para editar los datos personales.
7. Posibilidad de dejar evaluaciones:
Me gustaría poder dejar evaluaciones de libros comprados o leídos.

_Notas Adicionales:_
El diseño del dashboard debe integrarse de manera armoniosa con el navbar existente y otros componentes de la interfaz de usuario.
Se deben implementar medidas de seguridad adecuadas para proteger la información del usuario, especialmente en áreas como el historial de compras y los datos de envío.
El dashboard debe ser responsive y funcionar correctamente en dispositivos móviles para garantizar una experiencia de usuario consistente en todas las plataformas.
Esta historia de usuario aborda las necesidades del usuario que compra productos en la plataforma de ecommerce de libros, proporcionando un conjunto de características y funcionalidades que mejorarán su experiencia general y facilitarán el seguimiento de sus compras y envíos.

**Comment by nahir1009** [comment]
componente dashboard creado en Angular
