### ISSUE TITLE
#US09 #TK15: Desarrollar la interfaz del dashboard

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#58]
#TK15: (linkeada a la #US09)
#57 
_Descripción:_
Crear el diseño visual del dashboard del cliente que incluya secciones para cada una de las funcionalidades requeridas. El diseño debe integrarse de manera armoniosa con los componentes existentes de Angular, como el navbar y el footer.

_Criterios de aceptación:_

- Se ha diseñado una interfaz visual atractiva y funcional para el dashboard del cliente.
- El diseño incluye secciones claras y distinguibles para las funcionalidades de Resumen de Compras, Estado del Envío, Historial de Compras, etc.
- El diseño es responsive y se adapta correctamente a diferentes tamaños de pantalla y dispositivos.

_Tareas:_

- Crear los archivos de diseño para el dashboard.
- Diseñar las secciones para cada funcionalidad requerida, incluyendo Resumen de Compras, Estado del Envío, etc.
- Integrar el diseño con los componentes existentes de Angular, como el navbar y el footer.
- Realizar pruebas de compatibilidad y responsividad en diferentes dispositivos y tamaños de pantalla.

Se adjunta una imagen. La interfaz ya está creada, pero estática, respetando el diseño del desarrollo anterior del compañero, satisfacer los requerimientos del nuevo sprint:

![image](https://github.com/CodeSquadISPC/CodeSquadRepoFrontend/assets/100625720/f416f924-4aaa-4904-9fab-be8c0d96bcb3)
![image](https://github.com/CodeSquadISPC/CodeSquadRepoFrontend/assets/100625720/a7df987a-d00b-401b-a368-491b68a16660)

**Comment by nahir1009** [comment]
1)Se ha creado el componente dashboard con diseño de sidenab en Angular.
2)El diseño se ha integrado de manera acorde al navbar y footer
 3)se ha creado navbar con todas las funcionalidad
4) se creo diseño responsive
