### ISSUE TITLE
#US11: Implementación de Rutas Protegidas

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#67]
#US11: 

Como cliente autenticado, quiero que ciertas partes de la aplicación estén protegidas, de manera que solo pueda acceder a ellas si estoy autenticado.

_Criterios de Aceptación:_

1. Frontend - Rutas Protegidas:

- Las rutas definidas como protegidas solo deben ser accesibles si el usuario está autenticado.
- Si un usuario no autenticado intenta acceder a una ruta protegida, debe ser redirigido a la página de login.
- Las guardias de ruta deben verificar la validez del token de sesión antes de permitir el acceso.

**Comment by nahir1009** [comment]
se implemento rutas protegidas a través de guardias 
1) Las rutas definidas como protegidas solo deben ser accesibles si el usuario está autenticado: terminado
2 )Si un usuario no autenticado intenta acceder a una ruta protegida, debe ser redirigido a la página de login :implementado y terminado
