### ISSUE TITLE
#US11 #TK23: Implementación de Rutas Protegidas (routes)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#68]
#TK23 
1. Frontend - Rutas Protegidas en Angular:

- Implementar guardias de ruta para verificar autenticación antes de acceder a rutas protegidas.
- Redirigir a la página de login si el usuario no está autenticado.

2. Frontend - Manejo de Sesión:

- Implementar lógica para verificar la validez del token de sesión.
- Manejar expiración de sesión y redirección adecuada.

#67

**Comment by nahir1009** [comment]
implementación de rutas protegidas terminado:
 1) Se implemento guardias de ruta para verificar autenticación antes de acceder a rutas protegidas.
 2) Se redirecciona  a la página de login si el usuario no está autenticado.
3) mientras el usuario tenga la sección activada puede acceder a las rutas protegidas .
