### ISSUE TITLE
#TK04: Funcionalidades: Implementar migración de código a Angular (versión 17) en la Landing page (home)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#7]
#TK04

_Descripción:_
Se requiere migrar el código existente a Angular (versión 17) en la landing page (home) del frontend. Esta tarea implica la creación de un componente Landing y un componente Frase y su implementación dentro del componente Landing. Además, se considera opcional proporcionar datos mediante el enlace de datos (data binding) y mediante servicios.

_Criterios de aceptación:_

1. El componente Landing se ha creado y se ha integrado correctamente.
2. El componente Frase se ha creado y se ha integrado correctamente.
3. Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.
4. Opcionalmente, se han utilizado servicios para proporcionar datos.

Si los elementos opcionales no se completan en este Sprint, se creará un nuevo issue enlazado al Sprint 2 para un desarrollo futuro.

Asociado a la historia de usuario(#US06): #40 

![landing](https://github.com/CodeSquadISPC/CodeSquadRepo/assets/100625720/eff69ccf-6950-4af3-9a2b-c7487bbeafde)

**Comment by Leopladom** [comment]
Criterios de aceptación:

El componente Landing se ha creado y se ha integrado correctamente.
El componente Frase se ha creado y se ha integrado correctamente.
Opcionalmente, se ha realizado el enlace de datos (data binding) para proveer datos dinámicamente.


Este opcional queda para un proximo desarrollo:
Opcionalmente, se han utilizado servicios para proporcionar datos.


Asociado a la historia de usuario(#US06): https://github.com/CodeSquadISPC/CodeSquadRepoFrontend/issues/40
