### ISSUE TITLE
#US05 #TK26: Implementación del Carrito de Compras (pasarela de pago dashboard)

### ISSUE THREAD

**Issue by IvetteJN** [CodeSquadISPC/CodeSquadRepoFrontend#71]
#TK26
1. Frontend - Pasarela de Pago:

- Implementar formulario de pago y validaciones.
- Conectar con una API de pago de prueba.
- Manejar respuestas de éxito o error y mostrar mensajes personalizados al usuario.

#22

**Comment by IvetteJN** [comment]
#22

**Comment by nahir1009** [comment]
Pasarela de pago con api de mercado pago implementada. Con respuestas de éxito y error integradas.
